/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedCardRouteImport } from './routes/_authenticated/card'
import { Route as AuthenticatedConnectBalanceRouteImport } from './routes/_authenticated/connect-balance'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedPaymentAddressRouteImport } from './routes/_authenticated/payment-address'
import { Route as AuthenticatedPayoutsRouteImport } from './routes/_authenticated/payouts'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedTransactionsRouteImport } from './routes/_authenticated/transactions'
import { Route as AuthenticatedWithdrawRouteImport } from './routes/_authenticated/withdraw'

const AuthenticatedCardRoute = AuthenticatedCardRouteImport.update({
  id: '/_authenticated/card',
  path: '/card',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConnectBalanceRoute =
  AuthenticatedConnectBalanceRouteImport.update({
    id: '/_authenticated/connect-balance',
    path: '/connect-balance',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/_authenticated/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPaymentAddressRoute =
  AuthenticatedPaymentAddressRouteImport.update({
    id: '/_authenticated/payment-address',
    path: '/payment-address',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPayoutsRoute = AuthenticatedPayoutsRouteImport.update({
  id: '/_authenticated/payouts',
  path: '/payouts',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/_authenticated/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/_authenticated/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTransactionsRoute =
  AuthenticatedTransactionsRouteImport.update({
    id: '/_authenticated/transactions',
    path: '/transactions',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedWithdrawRoute = AuthenticatedWithdrawRouteImport.update({
  id: '/_authenticated/withdraw',
  path: '/withdraw',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/card': typeof AuthenticatedCardRoute
  '/connect-balance': typeof AuthenticatedConnectBalanceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/payment-address': typeof AuthenticatedPaymentAddressRoute
  '/payouts': typeof AuthenticatedPayoutsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/support': typeof AuthenticatedSupportRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/withdraw': typeof AuthenticatedWithdrawRoute
}
export interface FileRoutesByTo {
  '/card': typeof AuthenticatedCardRoute
  '/connect-balance': typeof AuthenticatedConnectBalanceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/payment-address': typeof AuthenticatedPaymentAddressRoute
  '/payouts': typeof AuthenticatedPayoutsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/support': typeof AuthenticatedSupportRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/withdraw': typeof AuthenticatedWithdrawRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/card': typeof AuthenticatedCardRoute
  '/_authenticated/connect-balance': typeof AuthenticatedConnectBalanceRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/payment-address': typeof AuthenticatedPaymentAddressRoute
  '/_authenticated/payouts': typeof AuthenticatedPayoutsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRoute
  '/_authenticated/withdraw': typeof AuthenticatedWithdrawRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/card'
    | '/connect-balance'
    | '/dashboard'
    | '/payment-address'
    | '/payouts'
    | '/profile'
    | '/support'
    | '/transactions'
    | '/withdraw'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/card'
    | '/connect-balance'
    | '/dashboard'
    | '/payment-address'
    | '/payouts'
    | '/profile'
    | '/support'
    | '/transactions'
    | '/withdraw'
  id:
    | '__root__'
    | '/_authenticated/card'
    | '/_authenticated/connect-balance'
    | '/_authenticated/dashboard'
    | '/_authenticated/payment-address'
    | '/_authenticated/payouts'
    | '/_authenticated/profile'
    | '/_authenticated/support'
    | '/_authenticated/transactions'
    | '/_authenticated/withdraw'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedCardRoute: typeof AuthenticatedCardRoute
  AuthenticatedConnectBalanceRoute: typeof AuthenticatedConnectBalanceRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPaymentAddressRoute: typeof AuthenticatedPaymentAddressRoute
  AuthenticatedPayoutsRoute: typeof AuthenticatedPayoutsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedTransactionsRoute: typeof AuthenticatedTransactionsRoute
  AuthenticatedWithdrawRoute: typeof AuthenticatedWithdrawRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/card': {
      id: '/_authenticated/card'
      path: '/card'
      fullPath: '/card'
      preLoaderRoute: typeof AuthenticatedCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/connect-balance': {
      id: '/_authenticated/connect-balance'
      path: '/connect-balance'
      fullPath: '/connect-balance'
      preLoaderRoute: typeof AuthenticatedConnectBalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/payment-address': {
      id: '/_authenticated/payment-address'
      path: '/payment-address'
      fullPath: '/payment-address'
      preLoaderRoute: typeof AuthenticatedPaymentAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/payouts': {
      id: '/_authenticated/payouts'
      path: '/payouts'
      fullPath: '/payouts'
      preLoaderRoute: typeof AuthenticatedPayoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/withdraw': {
      id: '/_authenticated/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof AuthenticatedWithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedCardRoute: AuthenticatedCardRoute,
  AuthenticatedConnectBalanceRoute: AuthenticatedConnectBalanceRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPaymentAddressRoute: AuthenticatedPaymentAddressRoute,
  AuthenticatedPayoutsRoute: AuthenticatedPayoutsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedTransactionsRoute: AuthenticatedTransactionsRoute,
  AuthenticatedWithdrawRoute: AuthenticatedWithdrawRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
